---
- name: Check gcloud sdk directory exists
  stat:
    path: /usr/local/google-cloud-sdk
  register: gcloud_exists

- name: Downloading google cloud sdk script
  get_url: url=https://dl.google.com/dl/cloudsdk/channels/rapid/install_google_cloud_sdk.bash dest=/tmp/install_google_cloud_sdk.bash
  when: gcloud_exists.stat.isdir is not defined

- name: Change file ownership, group and permissions
  file:
    path: /tmp/install_google_cloud_sdk.bash
    mode: '0755'
  when: gcloud_exists.stat.isdir is not defined

- name: Execute the install_google_cloud_sdk.bash
  shell: /tmp/install_google_cloud_sdk.bash --disable-prompts --install-dir={{ gcloud_install_dir }}
  when: gcloud_exists.stat.isdir is not defined

- name: updating alternatives
  command: "update-alternatives --install /usr/bin/{{ item }} {{ item }} /usr/local/google-cloud-sdk/bin/{{ item }} 1 --force"
  loop:
    - "gsutil"
    - "gcloud"
  when: ansible_os_family == 'Suse'
... 