---
- name: install packages
  package:
    name: "{{ package_list }}"
    state: present
  register: result
  retries: "{{ package_retries_cnt }}"
  until: result.rc == 0
  delay: "{{ package_retries_delay }}"

- name: Disable SELinux
  selinux:
    state: disabled
  register: result
  failed_when: result.msg | default('ok', True) is not search('(^ok$|libselinux-python|(SELinux state changed))')

- sysctl:
    name: "{{ item }}"
    value: '0'
    sysctl_set: yes
    state: present
    reload: yes
  loop:
    - vm.pagecache_limit_mb
    - vm.pagecache_limit_ignore_dirty
    - net.ipv4.tcp_slow_start_after_idle
    - kernel.numa_balancing
  when: ansible_facts['distribution'] == "SLES_SAP"
...
