---

- name: Copy RPM based SAPHOSTAGENT to the target host
  copy:
    src: "{{ sap_hostagent_rpm_local_path }}/{{ sap_hostagent_rpm_file_name }}"
    dest: "{{ sap_hostagent_agent_tmp_directory }}/{{ sap_hostagent_rpm_file_name }}"
  when: sap_hostagent_rpm_local_path is defined

- name: Ensure RPM file is installed
  yum:
    name: "{{ sap_hostagent_agent_tmp_directory }}/{{ sap_hostagent_rpm_file_name }}"
    state: present
  when: sap_hostagent_rpm_local_path is defined
  register: rpm_is_installed
  until: rpm_is_installed is succeeded
  retries: 30
  delay: 10

- name: Ensure RPM file is installed
  yum:
    name: "{{ sap_hostagent_rpm_remote_path }}/{{ sap_hostagent_rpm_file_name }}"
    state: present
  when: sap_hostagent_rpm_remote_path is defined
  register: rpm_is_installed
  until: rpm_is_installed is succeeded
  retries: 30
  delay: 10

# #Remove sapadm user and sapsys group created by the yum hostagent install command from above
# - name: Get sapadm user running processes
#   shell: "ps -ef | grep -v grep | grep -w sapadm | awk '{print $2}'"
#   register: running_processes

# - name: Force kill stuck processes
#   shell: "kill -9 {{ item }}"
#   with_items: "{{ running_processes.stdout_lines }}"

# - name: Remove the user "sapadm"
#   user:
#     name: sapadm
#     state: absent
#     remove: yes
#   run_once: true

# - name: check if "sapsys" group is empty
#   shell: |
#     lid -g sapsys
#   register: sapsys_group
#   failed_when: false

# - name: Remove the group "sapsys"
#   group:
#     name: sapsys
#     state: absent
#   when: sapsys_group.stdout == ""