---
- name: Ensure destination directory is present
  file:
    path: '{{ sap_nw_install_files_dest }}'
    mode: 0755
    state: directory

- name: Copy netweaver binaries from GC
  command: >-
    gsutil -m rsync -r
    gs://{{ sap_nw_install_files_bucket }}/{{ sap_nw_install_files_bucket_prefix }}/{{ item }}
    {{ sap_nw_install_files_dest }}
  with_items: "{{ storage }}"
  environment:
    CLOUDSDK_PYTHON: '{{ cloudsdk_python_export_path }}'
