---
- name: Export cloudsdk python path
  set_fact:
    cloudsdk_python_export_path: /usr/bin/python3
  when: ansible_os_family == 'Suse' and ansible_distribution_major_version == '15'

- name: Ensure destination directory is present
  file:
    path: '{{ sap_nw_install_files_dest }}/{{ item }}'
    mode: 0755
    state: directory
  with_items: "{{ sap_product_vars[sap_product_and_version].install_files }}"

- name: Define bucket and prefix
  set_fact:
    sap_nw_install_files_bucket_and_prefix: '{{ sap_nw_install_files_bucket }}'
  when: |
    '/' in sap_nw_install_files_bucket

- name: Define bucket and prefix
  set_fact:
    sap_nw_install_files_bucket_and_prefix: '{{ sap_nw_install_files_bucket }}/{{ sap_product_and_version }}'
  when: |
    '/' not in sap_nw_install_files_bucket

- name: Copy netweaver binaries from GC
  command: >-
    gsutil -m rsync -r
    gs://{{ sap_nw_install_files_bucket_and_prefix }}/{{ item }} {{ sap_nw_install_files_dest }}/{{ item }}
  with_items: "{{ sap_product_vars[sap_product_and_version].install_files }}"
  environment:
    CLOUDSDK_PYTHON: '{{ cloudsdk_python_export_path }}'
