---
- name: Create a software directory
  file:
    path: /sapmnt/Software
    state: directory
    mode: '0775'
- name: Copy netweaver binaries from GC
  shell: |
    gsutil -m cp -r gs://{{ nw_bucket }}/{{ folder }}/{{ item }} /sapmnt/Software
  with_items: "{{ storage }}"
    environment:
    CLOUDSDK_PYTHON: "{{ cloudsdk_python_export_path }}"

