steps:
- name: python:3.8.4-slim
  args:
  - /bin/sh
  - -c
  - |
    packer build \
      -var project-id=albatross-duncanl-sandbox-2 \
      -var subnetwork=app2 \
      -var image-version=v5 \
      -var awx-version=13.0.0 \
      build.json
