steps:
- name: python:3.8.4-slim
  args:
  - /bin/sh
  - -c
  - |
    set -e

    packer_version=1.6.0
    packer_archive=packer_${packer_version}_linux_amd64.zip

    apt update
    apt install -y --no-install-recommends \
      curl \
      unzip

    curl -LO https://releases.hashicorp.com/packer/${packer_version}/${packer_archive}
    unzip ${packer_archive}

    ./packer build \
      -var project-id=${PROJECT_ID} \
      -var subnetwork=default \
      -var image-version=v5 \
      -var awx-version=13.0.0 \
      build.json
