- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
  - name: expand awx installer inventory variables
    template:
      src: inventory/host_vars/default.j2
      dest: '{{ playbook_dir }}/inventory/host_vars/default'

- hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: install packages
    apt:
      name:
      - docker.io
      - docker-compose
      - git
      - python3-docker
      - python3-venv
