- name: SAP NW deploy
  hosts: 127.0.0.1
  connection: local
  roles:
  - role: forminator
    vars:
      sap_tf_project_path: './tf'
      sap_tf_state_bucket_prefix: '{{ sap_ascs_instance_name }}'
      sap_tf_state_bucket: '{{ sap_state_bucket }}'
      sap_tf_variables:
        project_id: '{{ sap_project_id }}'
        ascs_instance_name: '{{ sap_ascs_instance_name }}'
        ers_instance_name: '{{ sap_ers_instance_name }}'
        pas_instance_name: '{{ sap_pas_instance_name }}'
        ascs_zone: '{{ sap_ascs_zone }}'
        ers_zone: '{{ sap_ers_zone }}'
        pas_zone: '{{ sap_zone }}'
        ascs_healthcheck_port: '{{ sap_nw_ascs_health_check_port }}'
        ers_healthcheck_port: '{{ sap_nw_ers_health_check_port }}'
        region: '{{ sap_region }}'
        instance_type: '{{ sap_nw_instance_type }}'
        source_image_family: '{{ sap_source_image_family }}'
        source_image_project: '{{ sap_source_image_project }}'
        network: '{{ sap_network }}'
        subnetwork_project: '{{ sap_subnetwork_project_id }}'
        boot_disk_size: '{{ sap_nw_boot_disk_size }}'
        service_account_email: '{{ sap_nw_service_account_email }}'
        subnetwork: '{{ sap_subnetwork }}'
        gce_ssh_user: '{{ sap_ssh_user }}'
        gce_ssh_pub_key_file: '{{ sap_ssh_pub_key }}'
- name: SAP NW configure
  hosts: nodes
  become: yes
  become_user: root  
  roles:
  - role: netweaver-ha
- name: SAP NW configure
  hosts: pas
  become: yes
  become_user: root
  roles:
  - role: netweaver-ha
