---

- name: Run hana db backup
  shell: |
    source /usr/sap/{{ sap_hana_user }}/home/.sapenv.sh && \
    /usr/sap/{{ sap_hana_sid | upper }}/HDB{{ sap_hana_instance_number }}/exe/hdbsql \
    -i {{ sap_hana_instance_number }} -u SYSTEM -p {{ sap_hana_db_system_password }} -d SYSTEMDB -m <<EOF
    BACKUP DATA FOR {{ sap_hana_sid }} USING FILE ('{{ sap_hana_backup_file_name }}');
    EOF
  args:
     executable: /bin/bash
  become: yes
  become_user: "{{ sap_hana_user }}"
  register: hanabackup
  changed_when: "'0 rows affected' in hanabackup.stdout"
  when:
    - '"-pri" in "{{ ansible_hostname }}"'

- name: Run system db backup
  shell: |
    source /usr/sap/{{ sap_hana_user }}/home/.sapenv.sh && \
    /usr/sap/{{ sap_hana_sid | upper }}/HDB{{ sap_hana_instance_number }}/exe/hdbsql \
    -i {{ sap_hana_instance_number }} -u SYSTEM -p {{ sap_hana_db_system_password }} -d SYSTEMDB -m <<EOF
    BACKUP DATA USING FILE ('{{ sap_hana_backup_file_name }}_SYSTEMDB');
    EOF
  args:
     executable: /bin/bash
  become: yes
  become_user: "{{ sap_hana_user }}"
  register: systembackup
  changed_when: "'0 rows affected' in systembackup.stdout"
  when:
    - '"-pri" in "{{ ansible_hostname }}"'
