---
- name: permissions to home 
  file:
    path: /usr/sap
    state: directory
    mode: 0777
    recurse: true
- name: changing permissions
  file:
    path: /sapmnt
    state: directory
    mode: 0777
    recurse: true
- name: Create a software directory
  file:
    path: /sapmnt/{{ ascs_sid }}
    state: directory
    mode: '0775'    
- name: Setting fact for nw installer path
  set_fact:
    sapinst_path: "{{ sap_deployment_sapcar_path }}"
- name: inifile.params config file 
  template:
    src: "{{ sap_nw_ini_template }}"
    dest: /usr/sap/inifile_ascs.params  
- name: installing ascs
  command: >- 
     ./sapinst SAPINST_USE_HOSTNAME={{ sap_nw_ascs_virtual_host }} \
     SAPINST_INPUT_PARAMETERS_URL=/usr/sap/inifile_ascs.params \
     SAPINST_EXECUTE_PRODUCT_ID={{ sap_nw_product_id }} \
     SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false
  args:
    chdir: "{{ sap_nw_sapcar_path }}"
