---
- name: permissions to home 
  file:
    path: /tmp/sapinst_instdir
    state: directory
    mode: 0775
    recurse: true

- name: changing permissions
  file:
    path: /sapmnt
    state: directory
    mode: 0775
    recurse: true

- name: inifile.params config file
  template:
    src: inifile.params.j2
    dest: /usr/sap/inifile_ascs.params

- name: check for files created by ascs installer
  stat:
    path: '{{ item }}'
  loop:
  - '/usr/sap/{{ sap_nw_sid }}/ASCS{{ sap_nw_ascs_instance_number }}/exe/sapcontrol'
  - '/sapmnt/{{ sap_nw_sid }}/profile/{{ sap_nw_sid }}_ASCS{{ sap_nw_ascs_instance_number }}_{{ sap_nw_ascs_virtual_host }}'
  register: ascs_installed_files

- name: installing ascs
  command: >- 
     ./sapinst SAPINST_INPUT_PARAMETERS_URL=/usr/sap/inifile_ascs.params \
     SAPINST_EXECUTE_PRODUCT_ID={{ sap_nw_product_id }} \
     SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false
  register: installnw
  args:
    chdir: "{{ sap_product_vars[sap_product_and_version].sap_nw_sapcar_path }}"
  when: false in ascs_installed_files.results | map(attribute="stat") | map(attribute="exists") | list
