---
- name: permissions to home 
  file:
    path: /tmp/sapinst_instdir
    state: directory
    mode: 0775
    recurse: true

- name: changing permissions
  file:
    path: /sapmnt
    state: directory
    mode: 0775
    recurse: true

- name: inifile.params config file 
  template:
    src: "{{ sap_nw_ini_template }}"
    dest: /usr/sap/inifile_ascs.params  
- name: installing ascs
  command: >- 
     ./sapinst SAPINST_INPUT_PARAMETERS_URL=/usr/sap/inifile_ascs.params \
     SAPINST_EXECUTE_PRODUCT_ID={{ sap_nw_product_id }} \
     SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false
  register: installnw
  args:
    chdir: "{{ sap_nw_sapcar_path }}"
  when: true
