---

- name: Include base role
  include_role:
    name: base

- name: Include storage role
  include_role:
    name: storage

- name: Include hana packages download role
  include_role:
    name: sap-hana-download-packages

- name: Include common role
  include_role:
    name: common

- name: Include SAP hostagent install role
  include_role:
    name: sap-hostagent

- name: Include sap pre-configure role
  include_role:
    name: sap-preconfigure
  when: sap_image_family == "RedHat"

- name: Include sap hana pre-configure role
  include_role:
    name: sap-hana-preconfigure
  when: sap_image_family == "RedHat"

- name: Include sap hana install role
  include_role:
    name: sap-hana-install

- name: Include sap hana start role
  include_role:
    name: sap-hana-start

- name: Include sap hana ssfs copy keys role
  include_role:
    name: sap-hana-ssfs-keys

- name: Include sap hana backup config role
  include_role:
    name: sap-hana-config-backup

- name: Include sap hana hdb user create role
  include_role:
    name: sap-hana-hdb-user

- name: Include sap hana hdb userstore role
  include_role:
    name: sap-hana-hdb-userstore

- name: Include sap hana backup role
  include_role:
    name: sap-hana-backup

- name: Include sap hana hsr config role
  include_role:
    name: sap-hana-hsr

- name: Include pacemaker install/config role
  include_role:
    name: pacemaker-hana