---
- name: permissions to home 
  file:
    path: /usr/sap
    state: directory
    mode: 0777
    recurse: true

- name: changing permissions
  file:
    path: /sapmnt
    state: directory
    mode: 0777
    recurse: true

- name: inifile.params config file 
  template:
    src: "{{ sap_nw_ini_template }}"
    dest: /usr/sap/inifile_db.params
    
- name: installing s4-hana 
  command: >- 
     ./sapinst SAPINST_INPUT_PARAMETERS_URL=/usr/sap/inifile_db.params \
     SAPINST_EXECUTE_PRODUCT_ID={{ sap_nw_product_id }} \
     SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false
  register: installnw
  args:
    chdir: "{{ sap_nw_sapcar_path }}"
