---
- name: permissions to home 
  file:
    path: /usr/sap
    state: directory
    mode: 0777
    recurse: true

- name: changing permissions
  file:
    path: /sapmnt
    state: directory
    mode: 0777
    recurse: true

- name: inifile.params config file 
  template:
    src: "{{ sap_nw_ini_template }}"
    dest: /usr/sap/inifile_db.params

- name: check for files created by db installer
  stat:
    path: '{{ item }}'
  loop:
  - /home/{{ sap_nw_user }}/.hdb/{{ sap_nw_pas_virtual_host }}
  - /sapmnt/{{ sap_nw_ascs_sid }}/exe/uc/linuxx86_64/R3load
  register: db_installed_files
    
- name: installing s4-hana 
  command: >- 
     ./sapinst SAPINST_INPUT_PARAMETERS_URL=/usr/sap/inifile_db.params \
     SAPINST_EXECUTE_PRODUCT_ID={{ sap_nw_product_id }} \
     SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false
  register: installnw
  args:
    chdir: "{{ sap_product_vars[sap_product_and_version].sap_nw_sapcar_path }}"
  when: false in db_installed_files.results | map(attribute="stat") | map(attribute="exists") | list
