---

sap_nw_std_usr_sap_size: 140G
sap_nw_std_sap_mnt_size: 140G
sap_nw_std_swap_size: 29G
sap_nw_std_bucket_prefix: nw75/Software
sap_nw_std_product_id: "NW_ABAP_OneHost:NW750.HDB.ABAP"
sap_nw_std_template: "inifile.params.standard.j2"
sap_nw_std_sapinst_package_kernel: /sapmnt/Software/Kernel_Files
sap_nw_std_sapcryptofile: SAPEXE_200-80002573.SAR
sap_nw_std_igs_file_name: igsexe_4-80003187.sar
sap_nw_std_igs_helper_file_name: igshelper_17-10010245.sar
sap_nw_std_sapexedbsar: SAPEXEDB_200-80002572.SAR
sap_nw_std_sapexesar: SAPEXE_200-80002573.SAR
sap_nw_std_sapcar_path: /sapmnt/Software/SWPM1.0
sap_nw_std_sapinst_package_load: /sapmnt/Software/NW75
sap_nw_std_sapinst_package_client: /sapmnt/Software/HANA_CLIENT
sap_nw_std_archives_downloadbasket: /sapmnt/Software/Kernel_Files

sap_deployment_ascs_instance_nr: "00"
sap_deployment_pas_instance_nr: "01"
