---
- name: SAP HANA deploy
  hosts: 127.0.0.1
  connection: local
  vars:
    sap_hostagent_file_name: saphostagentrpm_44-20009394.rpm
    sap_hana_bundle_file_name: IMDB_SERVER20_047_0-80002031.SAR
    sap_hana_sapcar_file_name: SAPCAR_1320-80000935.EXE
    sap_hana_boot_disk_size: 30
    sap_gce_ssh_user: ansible
  roles:
  - role: forminator
    vars:
      sap_state_bucket_prefix: '{{ sap_instance_name }}'
      sap_tf_project_path: './tf'
      sap_state: '{{ state | default("present") }}'
      sap_tfvars:
        boot_disk_size: '{{ sap_hana_boot_disk_size }}'
        gce_ssh_user: '{{ sap_gce_ssh_user }}'
        gce_ssh_pub_key_file: '{{ playbook_dir }}/ssh-key.pub'
        instance_name: '{{ sap_instance_name }}'
        instance_type: '{{ sap_instance_type }}'
        linux_image_family: '{{ sap_linux_image_family }}'
        linux_image_project: '{{ sap_linux_image_project }}'
        project_id: '{{ sap_project_id }}'
        sap_install_files_bucket: '{{ sap_install_files_bucket }}'
        sap_hostagent_file_name: '{{ sap_hostagent_file_name }}'
        sap_hana_bundle_file_name: '{{ sap_hana_bundle_file_name }}'
        sap_hana_sapcar_file_name: '{{ sap_hana_sapcar_file_name }}'
        service_account_email: '{{ sap_service_account_email }}'
        subnetwork: '{{ sap_subnetwork }}'
        subnetwork_project: '{{ sap_subnetwork_project }}'
        zone: '{{ sap_zone }}'

- name: SAP HANA configure
  hosts: hana
  vars:
    sap_image_family: '{{ terraform.outputs.sap_image_family.value }}'
    sap_hana_data_partition_name: hanadata
    sap_hana_backup_partition_name: hanabackup
    sap_hana_deployment_hana_instance_number: '{{ sap_hana_instance_number }}'
    sap_hana_deployment_hana_sid: '{{ sap_hana_sid }}'
    sap_hana_deployment_hostagent_file_name: '{{ terraform.outputs.sap_hostagent_file_name.value }}'
    sap_hana_deployment_bundle_sar_file_name: '{{ terraform.outputs.sap_hana_bundle_file_name.value }}'
    sap_hana_deployment_sapcar_file_name: '{{ terraform.outputs.sap_hana_sapcar_file_name.value }}'
  roles:
  - role: sap-hana-download-packages
  - role: storage
    vars:
      hana_shared_size: '{{ terraform.outputs.hana_shared_size.value }}G'
      hana_data_size: '{{ terraform.outputs.hana_data_size.value }}G'
      hana_log_size: '{{ terraform.outputs.hana_log_size.value }}G'
      hana_usr_size: '{{ terraform.outputs.hana_usr_size.value }}G'
      hana_backup_size: '{{ terraform.outputs.hana_backup_size.value - 1 }}G'
      swapon: false
      disks:
        - { name: hana0-data, partition_path: "{{ sap_hana_data_partition_name }}" }
        - { name: hana1-backup, partition_path: "{{ sap_hana_backup_partition_name }}" }
      logvols:
        shared:
          size: "{{ hana_shared_size }}"
          vol: hanadata 
          mountpoint: /hana/shared
          fstype: xfs
        data:
          size: "{{ hana_data_size }}"
          vol: hanadata
          mountpoint: /hana/data
          fstype: xfs
        log:
          size: "{{ hana_log_size }}"
          vol: hanadata
          mountpoint: /hana/log
          fstype: xfs
        usr:
          size: "{{ hana_usr_size }}"
          vol: hanadata
          mountpoint: /usr/sap
          fstype: xfs
        backup:
          size: "{{ hana_backup_size}}"
          vol: hanabackup
          mountpoint: /hanabackup
          fstype: xfs

  - role: common
    vars:
      sap_hostagent_file_name: '{{ terraform.outputs.sap_hostagent_file_name.value }}'
      sap_hana_bundle_file_name: '{{ terraform.outputs.sap_hana_bundle_file_name.value }}'
      sap_hana_sapcar_file_name: '{{ terraform.outputs.sap_hana_sapcar_file_name.value }}'

  - role: sap-hostagent
    vars:
      sap_hostagent_rpm_remote_path: "/hana/shared/software"
      sap_hostagent_rpm_file_name: '{{ terraform.outputs.sap_hostagent_file_name.value }}'

  - role: sap-preconfigure
    vars:
      sap_preconfigure_modify_etc_hosts: true
      sap_domain: automation.local
    when: sap_image_family == "RedHat"

  - role: sap-hana-preconfigure
    when: sap_image_family == "RedHat"

  - role: sap-hana-install
    vars:
      sap_hana_deployment_bundle_sar_file_name: '{{ terraform.outputs.sap_hana_bundle_file_name.value }}'
      sap_hana_deployment_sapcar_file_name: '{{ terraform.outputs.sap_hana_sapcar_file_name.value }}'
      sap_hana_deployment_root_password: Google123
      sap_hana_deployment_sapadm_password: Google123
      sap_hana_deployment_hana_env_type: development
      sap_hana_deployment_hana_mem_restrict: "n"
      sap_hana_deployment_common_master_password: Google123
      sap_hana_deployment_ase_user_password: Google123
      sap_hana_deployment_sidadm_password: Google123
      sap_hana_deployment_hana_db_system_password: Google123
      sap_hana_deployment_system_restart: "y"

  - role: sap-hana-start
