---
- name: SAP HANA deploy
  hosts: 127.0.0.1
  connection: local
  vars:
    sap_hostagent_file_name: saphostagentrpm_44-20009394.rpm
    sap_hana_bundle_file_name: IMDB_SERVER20_047_0-80002031.SAR
    sap_hana_sapcar_file_name: SAPCAR_1320-80000935.EXE
  tasks:
  - name: Copy ssh public key
    copy:
      dest: '{{ playbook_dir }}/ssh-key.pub'
      content: '{{ sap_hana_gce_ssh_pub_key }}'
  - name: Copy ssh private key
    copy:
      dest: '{{ playbook_dir }}/ssh-key'
      content: '{{ sap_hana_gce_ssh_priv_key }}'
      mode: '0600'
  - name: Deploy SAP HANA infrastructure
    terraform:
      backend_config:
        bucket: '{{ sap_hana_state_bucket }}'
        prefix: '{{ sap_hana_state_bucket_prefix | default(sap_hana_instance_name) }}'
      force_init: true
      project_path: ./tf
      state: present
      variables:
        instance_name: '{{ sap_hana_instance_name }}'
        linux_image_family: '{{ sap_hana_linux_image_family }}'
        linux_image_project: '{{ sap_hana_linux_image_project }}'
        region: '{{ sap_hana_region }}'
        zone: '{{ sap_hana_zone }}'
        subnetwork: '{{ sap_hana_subnetwork }}'
        boot_disk_size: '{{ sap_hana_boot_disk_size }}'
        sap_install_files_bucket: '{{ sap_install_files_bucket }}'
        sap_hostagent_file_name: '{{ sap_hostagent_file_name }}'
        sap_hana_bundle_file_name: '{{ sap_hana_bundle_file_name }}'
        sap_hana_sapcar_file_name: '{{ sap_hana_sapcar_file_name }}'
        gce_ssh_user: '{{ sap_hana_gce_ssh_user }}'
        gce_ssh_pub_key_file: '{{ playbook_dir }}/ssh-key.pub'
    register: terraform
  - name: Build inventory
    add_host:
      name: '{{ terraform.outputs.address.value }}'
      ansible_user: '{{ sap_hana_gce_ssh_user }}'
      ansible_ssh_private_key_file: '{{ playbook_dir }}/ssh-key'
      terraform: '{{ terraform }}'
      groups: hana
    changed_when: false
  - name: Wait for host
    shell: |-
      ssh -i {{ playbook_dir }}/ssh-key \
        -o StrictHostKeyChecking=no \
        {{ sap_hana_gce_ssh_user }}@{{ terraform.outputs.address.value }} \
        exit
    register: can_ssh
    retries: 12
    delay: 10
    until: can_ssh is succeeded

- name: SAP HANA configure
  hosts: hana
  vars:
    sap_image_family: '{{ terraform.outputs.sap_image_family.value }}'
  roles:
  - role: storage
    vars:
      hana_shared_size: '{{ terraform.outputs.hana_shared_size.value }}G'
      hana_data_size: '{{ terraform.outputs.hana_data_size.value }}G'
      hana_log_size: '{{ terraform.outputs.hana_log_size.value }}G'
      hana_usr_size: '{{ terraform.outputs.hana_usr_size.value }}G'
      hana_backup_size: '{{ terraform.outputs.hana_backup_size.value - 1 }}G'

  - role: common
    vars:
      sap_hostagent_file_name: '{{ terraform.outputs.sap_hostagent_file_name.value }}'
      sap_hana_bundle_file_name: '{{ terraform.outputs.sap_hana_bundle_file_name.value }}'
      sap_hana_sapcar_file_name: '{{ terraform.outputs.sap_hana_sapcar_file_name.value }}'

  - role: sap-hostagent
    vars:
      sap_hostagent_installation_type: "rpm"          # Use "Zypper" for Suse systems
      sap_hostagent_rpm_remote_path: "/hana/shared/software"
      sap_hostagent_rpm_file_name: '{{ terraform.outputs.sap_hostagent_file_name.value }}'

  - role: sap-preconfigure
    vars:
      sap_preconfigure_modify_etc_hosts: true
      sap_domain: automation.local
    when: sap_image_family == "RedHat"

  - role: sap-hana-preconfigure
    when: sap_image_family == "RedHat"

  - role: sap-hana-install
    vars:
      sap_hana_deployment_bundle_sar_file_name: '{{ terraform.outputs.sap_hana_bundle_file_name.value }}'
      sap_hana_deployment_sapcar_file_name: '{{ terraform.outputs.sap_hana_sapcar_file_name.value }}'
      sap_hana_deployment_hana_sid: RH1
      sap_hana_deployment_root_password: Google123
      sap_hana_deployment_sapadm_password: Google123
      sap_hana_deployment_hana_instance_number: 00
      sap_hana_deployment_hana_env_type: development
      sap_hana_deployment_hana_mem_restrict: "n"
      sap_hana_deployment_common_master_password: Google123
      sap_hana_deployment_ase_user_password: Google123
      sap_hana_deployment_sidadm_password: Google123
      sap_hana_deployment_hana_db_system_password: Google123
      sap_hana_deployment_system_restart: "y"

  - role: sap-hana-start
    vars:
      sap_hana_deployment_hana_sid: RH1
