---
- name: SAP HANA deploy
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Copy ssh public key
    copy:
      dest: '{{ playbook_dir }}/ssh-key.pub'
      content: '{{ sap_hana_gce_ssh_pub_key }}'
  - name: Copy ssh private key
    copy:
      dest: '{{ playbook_dir }}/ssh-key'
      content: '{{ sap_hana_gce_ssh_priv_key }}'
      mode: '0600'
  - name: Deploy SAP HANA infrastructure
    terraform:
      project_path: ./tf
      force_init: true
      state: present
      variables:
        instance_name: '{{ sap_hana_instance_name }}'
        linux_image_family: '{{ sap_hana_linux_image_family }}'
        linux_image_project: '{{ sap_hana_linux_image_project }}'
        region: '{{ sap_hana_region }}'
        zone: '{{ sap_hana_zone }}'
        subnetwork: '{{ sap_hana_subnetwork }}'
        boot_disk_size: '{{ sap_hana_boot_disk_size }}'
        gce_ssh_user: '{{ sap_hana_gce_ssh_user }}'
        gce_ssh_pub_key_file: '{{ playbook_dir }}/ssh-key.pub'
        gce_ssh_priv_key_file: '{{ playbook_dir }}/ssh-key'
    register: terraform
  - name: Build inventory
    add_host:
      name: '{{ terraform.outputs.address.value }}'
      ansible_user: '{{ sap_hana_gce_ssh_user }}'
      ansible_ssh_private_key_file: '{{ playbook_dir }}/ssh-key'
      terraform: '{{ terraform }}'
      groups: hana
    changed_when: false
  - name: Wait for host
    shell: |-
      ssh -i {{ playbook_dir }}/ssh-key \
        -o StrictHostKeyChecking=no \
        {{ sap_hana_gce_ssh_user }}@{{ terraform.outputs.address.value }} \
        exit
    register: can_ssh
    retries: 12
    delay: 10
    until: can_ssh is succeeded

- name: SAP HANA configure
  hosts: hana
  roles:
  - role: storage
    storage_pools:
    - name: hana-data
      disks:
      - sdb
      volumes:
      - name: data
        size: '{{ terraform.outputs.hana_data_size.value }} GiB'
        mount_point: /hana/data
        state: present
      - name: shared
        size: '{{ terraform.outputs.hana_shared_size.value }} GiB'
        mount_point: /hana/shared
        state: present
      - name: log
        size: '{{ terraform.outputs.hana_log_size.value }} GiB'
        mount_point: /hana/log
        state: present
      - name: sap
        size: '{{ terraform.outputs.hana_usr_size.value }} GiB'
        mount_point: /usr/sap
        state: present
    - name: hana-backup
      disks:
      - sdc
      volumes:
      - name: backup
        size: '{{ terraform.outputs.hana_backup_size.value - 1 }} GiB'
        mount_point: /hana/backup
        state: present

  - role: sap-hostagent
    sap_hostagent_installation_type: rpm
    sap_hostagent_rpm_remote_path: /software/SAPHOSTAGENT
    sap_hostagent_rpm_file_name: saphostagentrpm_44-20009394.rpm

  - role: sap-preconfigure
    sap_preconfigure_modify_etc_hosts: true
    sap_domain: automation.local

  - role: sap-hana-preconfigure

  - role: sap-hana-deployment
    sap_hana_deployment_zip_path: /software/HANA_installation
    sap_hana_deployment_zip_file_name: 51053787.ZIP
    sap_hana_deployment_root_password: Google123
    sap_hana_deployment_sapadm_password: Google123
    sap_hana_deployment_hana_sid: RH2
    sap_hana_deployment_hana_instance_number: '01'
    sap_hana_deployment_hana_env_type: development
    sap_hana_deployment_hana_mem_restrict: n
    sap_hana_deployment_common_master_password: Google123
    sap_hana_deployment_sidadm_password: Google123
    sap_hana_deployment_hana_db_system_password: Google123
    sap_hana_deployment_ase_user_password: Google123
    sap_hana_deployment_apply_license: false
