---

- name: SAP HANA deploy
  hosts: 127.0.0.1
  connection: local
  roles:
  - role: forminator
    vars:
      sap_tf_state_bucket_prefix: '{{ sap_hana_instance_name }}'
      sap_tf_project_path: ./tf
      sap_state: '{{ state | default("present") }}'
      sap_tf_variables:
        boot_disk_size: '{{ sap_hana_boot_disk_size }}'
        instance_name: '{{ sap_hana_instance_name }}'
        instance_type: '{{ sap_hana_instance_type }}'
        linux_image_family: '{{ sap_linux_image_family }}'
        linux_image_project: '{{ sap_linux_image_project }}'
        project_id: '{{ sap_project_id }}'
        service_account_email: '{{ sap_hana_service_account_email }}'
        subnetwork: '{{ sap_subnetwork }}'
        subnetwork_project: '{{ sap_subnetwork_project }}'
        zone: '{{ sap_zone }}'

- name: SAP HANA configure
  hosts: hana
  become: yes
  vars:
    sap_image_family: '{{ terraform.outputs.sap_image_family.value }}'
    sap_hostagent_file_name: '{{ terraform.outputs.sap_hostagent_file_name.value }}'
    sap_hana_bundle_file_name: '{{ terraform.outputs.sap_hana_bundle_file_name.value }}'
    sap_hana_sapcar_file_name: '{{ terraform.outputs.sap_hana_sapcar_file_name.value }}'
    sap_hostagent_rpm_file_name: '{{ terraform.outputs.sap_hostagent_file_name.value }}'
    sap_hana_deployment_bundle_sar_file_name: '{{ terraform.outputs.sap_hana_bundle_file_name.value }}'
    sap_hana_deployment_sapcar_file_name: '{{ terraform.outputs.sap_hana_sapcar_file_name.value }}'
    hana_shared_size: '{{ terraform.outputs.hana_shared_size.value }}G'
    hana_data_size: '{{ terraform.outputs.hana_data_size.value }}G'
    hana_log_size: '{{ terraform.outputs.hana_log_size.value }}G'
    hana_usr_size: '{{ terraform.outputs.hana_usr_size.value }}G'
    hana_backup_size: '{{ terraform.outputs.hana_backup_size.value - 1 }}G'
    swapon: false
    disks:
      - { name: '{{ terraform.outputs.instance_attached_disks_data.value }}', partition_path : 'hanadata'}
      - { name: '{{ terraform.outputs.instance_attached_disks_backup.value }}', partition_path : 'hanabackup'}
    logvols:
      shared:
        size: "{{ hana_shared_size }}"
        vol: hanadata 
        mountpoint: /hana/shared
        fstype: xfs
      data:
        size: "{{ hana_data_size }}"
        vol: hanadata
        mountpoint: /hana/data
        fstype: xfs
      log:
        size: "{{ hana_log_size }}"
        vol: hanadata
        mountpoint: /hana/log
        fstype: xfs
      usr:
        size: "{{ hana_usr_size }}"
        vol: hanadata
        mountpoint: /usr/sap
        fstype: xfs
      backup:
        size: "{{ hana_backup_size}}"
        vol: hanabackup
        mountpoint: /hanabackup
        fstype: xfs
  roles:
  - role: sap-hana-scaleup
