---
- name: include pacemaker primary tasks
  include_role:
    name: pacemaker
    tasks_from: primary

- name: include pacemaker install tasks
  include_role:
    name: pacemaker
    tasks_from: install

- name: include pacemaker auth tasks
  include_role:
    name: pacemaker
    tasks_from: auth

- name: include pacemaker start-cluster tasks
  include_role:
    name: pacemaker
    tasks_from: start-cluster

- name: include pacemaker wait tasks
  include_role:
    name: pacemaker
    tasks_from: wait

- name: include pacemaker start-maintenance tasks
  include_role:
    name: pacemaker
    tasks_from: start-maintenance
  when: is_primary

- name: include pacemaker resources-general tasks
  include_role:
    name: pacemaker
    tasks_from: resources-general
  when: is_primary

- name: include pacemaker resources-stonith tasks
  include_role:
    name: pacemaker
    tasks_from: resources-stonith
  when: is_primary

- name: include pacemaker resources-vip tasks
  include_role:
    name: pacemaker
    tasks_from: resources-vip
  vars:
    sap_vip: '{{ item.vip }}'
    sap_vip_purpose: '{{ item.vip_purpose }}'
    sap_health_check_port: '{{ item.health_check_port }}'
    sap_use_lb: '{{ item.use_lb }}'
  loop:
  - vip: '{{ sap_ascs_vip }}'
    vip_purpose: ascs
    health_check_port: '{{ sap_ascs_health_check_port | default("") }}'
    use_lb: true
  - vip: '{{ sap_ers_vip }}'
    vip_purpose: ers
    health_check_port: '{{ sap_ers_health_check_port | default("") }}'
    use_lb: '{{ ansible_os_family == "Suse" }}'
  when: is_primary

- name: include pacemaker resources-netweaver tasks
  include_tasks: '{{ role_path }}/tasks/resources-netweaver.yml'
  when: is_primary

- name: include pacemaker stop-maintenance tasks
  include_role:
    name: pacemaker
    tasks_from: stop-maintenance
  when: is_primary
