galaxy_info:
  author: n/a
  description: Install Backint agent to create Hana backups
  company: n/a

  # TODO
  license: MIT

  min_ansible_version: 2.9

  # Provide a list of supported platforms, and for each platform a list of versions.
  # If you don't wish to enumerate all versions for a particular platform, use 'all'.
  # To view available platforms and versions (or releases), visit:
  # https://galaxy.ansible.com/api/v1/platforms/
  #
  platforms:
    - name: Centos
      versions:
        - 8
    - name: Fedora
      versions:
        - all

  galaxy_tags: []

dependencies: []
