---

- name: Export cloudsdk python path
  set_fact:
    cloudsdk_python_export_path: /usr/bin/python3
  when: ansible_os_family == 'Suse' and ansible_distribution_major_version == '15'

- name: Check if {{ sap_hostagent_rpm_remote_path }} dir exists
  stat:
    path: "{{ sap_hostagent_rpm_remote_path }}"
  register: software_dir

# Create software directory to store HANA install files
- name: Create {{ sap_hostagent_rpm_remote_path }} dir
  file:
    path: "{{ sap_hostagent_rpm_remote_path }}"
    state: directory
  when: software_dir.stat.exists == false

- name: Define bucket and prefix
  set_fact:
    sap_hana_install_files_bucket_and_prefix: '{{ sap_hana_install_files_bucket }}'
  when: |
    '/' in sap_hana_install_files_bucket

- name: Define bucket and prefix
  set_fact:
    sap_hana_install_files_bucket_and_prefix: '{{ sap_hana_install_files_bucket }}/{{ sap_product_and_version }}'
  when: |
    '/' not in sap_hana_install_files_bucket

- name: Download install files
  shell: |
    gsutil -m rsync -x '^(?!{{ item }}).*' -r gs://{{ sap_hana_install_files_bucket_and_prefix }} {{ sap_hostagent_rpm_remote_path }}
  args:
    creates: "{{ sap_hostagent_rpm_remote_path }}/{{ item }}"
  environment:
    CLOUDSDK_PYTHON: "{{ cloudsdk_python_export_path }}"
  with_items: "{{ sap_product_vars[sap_product_and_version].values() | list }}"

- name: Change SAP install file permissions
  file:
    path: "{{ sap_hostagent_rpm_remote_path }}"
    mode: '0775'
    recurse: yes
