---

- name: Export cloudsdk python path
  set_fact:
    cloudsdk_python_export_path: /usr/bin/python3
  when: ansible_os_family == 'Suse' and ansible_distribution_major_version == '15'

# Create software directory to store HANA install files
- name: Create /hana/shared/software dir
  file:
    path: /hana/shared/software
    state: directory

- name: Download HANA install files
  shell: |
    gsutil cp gs://{{ sap_install_files_bucket }}/{{ item }} /hana/shared/software
  args:
    creates: "/hana/shared/software/{{ item }}"
  environment:
    CLOUDSDK_PYTHON: "{{ cloudsdk_python_export_path }}"
  with_items:
    - "{{ sap_hostagent_rpm_file_name }}"
    - "{{ sap_hana_bundle_file_name }}"
    - "{{ sap_hana_sapcar_file_name }}"

- name: Change SAP install file permissions
  file:
    path: "/hana/shared/software/{{ item }}"
    mode: '0775'
  with_items:
    - "{{ sap_hostagent_rpm_file_name }}"
    - "{{ sap_hana_bundle_file_name }}"
    - "{{ sap_hana_sapcar_file_name }}"
  
