---  
- name: include base primary tasks
  include_role:
    name: base
- name: include storage primary tasks
  include_role:
    name: storage-bkup   
  vars:
    swapon: True
    nfs_mount: True
    subnet_cidr: '{{ terraform.outputs.subnet_cidr_nw.value }}'
    disks:
      - { name: sapmnt, partition_path : sapmnt }
      - { name: usrsap, partition_path : usrsap }
      - { name: swap, partition_path : swap }
    logvols:
      usrsap:
        size: "{{ sap_nw_usrsap_disk_size - 1 }}G"
        vol: usrsap
        mountpoint: /usr/sap
      sapmnt:
        size: "{{ sap_nw_sapmnt_disk_size - 1 }}G"
        vol: sapmnt
        mountpoint: /sapmnt
    swapvols:
      swap:
        size: "{{ sap_nw_swap_disk_size - 1 }}G"
        vol: swap 
        mountpoint: /swap 
- name: include nw-pre primary tasks
  include_role:
    name: nw-pre  
- name: include nw primary tasks
  include_role:
    name: ascs  
  vars:
    sap_nw_product_id: "{{ sap_product_vars[sap_product_and_version].ascs_product_id }}"
