---  
- name: include base primary tasks
  include_role:
    name: base
- name: include storage primary tasks
  include_role:
    name: storage-bkup
  vars:
    swapon: True
    subnet_cidr: '{{ terraform.outputs.subnet_cidr.value }}'
    disks:
      - { name: swap, partition_path : swap }
    swapvols:
      swap:
        size: "{{ sap_nw_swap_disk_size - 1 }}G"
        vol: swap
        mountpoint: /swap
    nfs_private_ip: '{{ terraform.outputs.nfs_private_ip.value }}'
    mountpa:
      usrsap: /usr/sap
      sapmnt: /sapmnt
- name: include nw-pre primary tasks
  include_role:
    name: nw-pre  
  vars: 
    nw_bucket: "{{ bucket }}"
    folder: "{{ path }}"
    storage: "{{ sap_nw_storage_files }}"
    cloudsdk_python_export_path: "{{ sap_nw_cloudsdk_python_export_path }}"    
- name: include db primary tasks    
  include_role:
    name: db
  vars:
    sap_nw_product_id: "{{ sap_nw_hana_product_id }}"
- name: include nw primary tasks
  include_role:
    name: nw
  vars:
    sap_nw_product_id: "{{ sap_nw_pas_product_id }}"
    sap_nw_installed_files:
    - '/sapmnt/{{ sap_nw_ascs_sid }}/profile/{{ sap_nw_ascs_sid }}_D{{ sap_nw_ci_instance_number }}_{{ sap_nw_pas_virtual_host }}'
    - '/usr/sap/{{ sap_nw_ascs_sid }}/D{{ sap_nw_ci_instance_number }}/exe/R3load'
