---

- name: SAP HANA deploy
  hosts: 127.0.0.1
  connection: local
  roles:
  - role: forminator
    vars:
      sap_tf_project_path: ./tf
      sap_ansible_is_push_mode: false
      sap_state: '{{ state | default("present") }}'
      sap_tf_variables:
        instance_name: '{{ sap_win_instance_name }}'
        project_id: '{{ sap_project_id }}'
        source_image_family: '{{ sap_source_image_family }}'
        source_image_project: '{{ sap_source_image_project }}'
        subnetwork: '{{ sap_subnetwork }}'
        service_account_email: '{{ sap_win_service_account_email | default("{}@{}.iam.gserviceaccount.com".format(sap_win_service_account_name | default("sap-common-sa"), sap_project_id)) }}'
        subnetwork_project: '{{ sap_subnetwork_project_id | default(sap_project_id) }}'
        zone: '{{ sap_zone | default("us-central1-a") }}'
        instance_type: '{{ sap_win_instance_type | default("e2-standard-2") }}'
        autodelete_disk: '{{ sap_win_autodelete_boot_disk | default(true) }}'
        boot_disk_size: '{{ sap_win_boot_disk_size | default(50) }}'
        boot_disk_type: '{{ sap_win_boot_disk_type | default("pd-ssd") }}'
        network_tags: '{{ sap_win_network_tags | default([sap_network_tag | default("sap-allow-all")]) }}'
        pd_kms_key: '{{ sap_win_pd_kms_key | default(None) }}'
        use_public_ip: '{{ sap_win_use_public_ip | default(false) }}'