---

- name: Group of tasks that are tightly coupled
  vars:
    max_retries: 5
    retry_delay: 10
  block:
    - name: Increment the retry count
      set_fact:
        retry_count: "{{ 0 if retry_count is undefined else retry_count | int + 1 }}"

    - name: 'Remove {{ sap_hana_gce_storage_client_path }}/gceStorageClient.pyc'
      file:
        path: '{{ sap_hana_gce_storage_client_path }}/gceStorageClient.pyc'
        state: absent

    - name: Create {{ sap_hana_sid }} directories in /hana/data and /hana/log
      file:
        path: "{{ item }}/{{ sap_hana_sid }}"
        state: directory
        mode: 0777
        recurse: true
      with_items:
        - "{{ sap_hana_data_mountpoint }}"
        - "{{ sap_hana_log_mountpoint }}"

    - name: Add standby nodes to master
      shell: |
        cat /root/.deploy/hana_passwords.xml | ./hdblcm --action=add_hosts --addhosts={{ sap_hana_instance_name }}w0{{ sap_instance_count_worker + sap_instance_count_standby }}:role=standby --root_user=root --listen_interface=global --read_password_from_stdin=xml -b
      args:
        chdir: "{{ sap_hana_shared_mountpoint }}/{{ sap_hana_sid }}/hdblcm/"
        creates: "/usr/sap/{{ sap_hana_sid }}/SYS/profile/{{ sap_hana_sid }}_HDB{{ sap_hana_instance_number }}_{{ sap_hana_instance_name }}w0{{ sap_instance_count_worker + sap_instance_count_standby }}"

  rescue:
    - fail:
        msg: Maximum retries of grouped tasks reached
      when: retry_count | int == max_retries | int

    - debug:
        msg: "Task Group failed, let's give it another shot"

    - name: Sleep between retries
      wait_for:
        timeout: "{{ retry_delay }}"
      delegate_to: localhost
      become: false

    - include_tasks: main.yml
