---

- name: Include storage role
  include_role:
    name: storage-delete

- name: Include common role
  include_role:
    name: common-delete

- name: Include SAP hostagent install role
  include_role:
    name: sap-hostagent

- name: Include sap pre-configure role
  include_role:
    name: sap-preconfigure
  when: sap_image_family == "RedHat"

- name: Include sap hana pre-configure role
  include_role:
    name: sap-hana-preconfigure
  when: sap_image_family == "RedHat"

- name: Include sap hana install role
  include_role:
    name: sap-hana-install

- name: Include sap hana start role
  include_role:
    name: sap-hana-start