---
- name: determine if node is primary
  set_fact:
    is_primary: '{{ ansible_default_ipv4.address == sap_primary_instance_ip }}'

- include_tasks: install.yml

- include_tasks: start-cluster.yml

- include_tasks: auth.yml

- include_tasks: wait.yml
  when: is_primary

- include_tasks: resources.yml
  when: is_primary
