---
- name: determine if node is primary
  set_fact:
    is_primary: '{{ ansible_default_ipv4.address == sap_primary_instance_ip }}'

- include_tasks: auth.yml

- name: ensure directories are present
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
    owner: root
    group: root
  loop:
  - /usr/lib/ocf/resource.d/gcp
  - /usr/lib64/stonith/plugins/external

- name: ensure files are downloaded
  uri:
    url: '{{ item.url }}'
    dest: '{{ item.dest }}'
    mode: 0755
    owner: root
    group: root
    remote_src: true
    follow_redirects: true
    status_code: [200, 304]
  loop:
  - url: https://storage.googleapis.com/sapdeploy/pacemaker-gcp/alias
    dest: /usr/lib/ocf/resource.d/gcp/alias
  - url: https://storage.googleapis.com/sapdeploy/pacemaker-gcp/route
    dest: /usr/lib/ocf/resource.d/gcp/route
  - url: https://storage.googleapis.com/sapdeploy/pacemaker-gcp/gcpstonith
    dest: /usr/lib64/stonith/plugins/external/gcpstonith

- name: ensure root can log in
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^PasswordAuthentication no'
    line: '#PasswordAuthentication no'
  register: modify_sshd_config
  when: |
    ansible_os_family == 'RedHat'

- name: ensure sshd reads modified config
  service:
    name: sshd.service
    state: restarted
  when: |
    ansible_os_family == 'RedHat' and modify_sshd_config is changed

- include_tasks: '{{ "primary" if is_primary else "secondary" }}-pre-{{ ansible_os_family | lower }}.yml'

- include_tasks: '{{ "primary" if is_primary else "secondary" }}-post-{{ ansible_os_family | lower }}.yml'
