---
- name: wait for cluster to be up
  command: crm_mon -s
  register: cluster_status
  retries: 30
  delay: 10
  until: |
    '2 nodes online' in cluster_status.stdout
  changed_when: false

- name: check maintenance mode
  command: crm configure get_property maintenance-mode
  register: maintenance_mode_status
  changed_when: false

- name: enable maintenance mode
  command: crm configure property maintenance-mode=true
  when: |
    maintenance_mode_status.stdout == 'false'

# TODO: add checks on the following commands for idempotency

- name: configure primitive stonith for primary
  command: >-
    crm configure primitive STONITH-"{{ sap_primary_instance }}" stonith:external/gcpstonith op monitor
    interval="300s" timeout="60s" on-fail="restart" op start interval="0" timeout="60s" onfail="restart"
    params instance_name="{{ sap_primary_instance }}" gcloud_path="{{ sap_gcloud_path }}" logging="yes"

- name: configure primitive stonith for secondary
  command: >-
    crm configure primitive STONITH-"{{ sap_secondary_instance }}" stonith:external/gcpstonith op monitor
    interval="300s" timeout="60s" on-fail="restart" op start interval="0" timeout="60s" onfail="restart"
    params instance_name="{{ sap_secondary_instance }}" gcloud_path="{{ sap_gcloud_path }}" logging="yes"

- name: configure location stonith for primary
  command: >-
    crm configure location LOC_STONITH_"{{ sap_primary_instance }}" STONITH-"{{ sap_primary_instance }}"
    -inf: "{{ sap_primary_instance }}"

- name: configure location stonith for secondary
  command: >-
    crm configure location LOC_STONITH_"{{ sap_secondary_instance }}" STONITH-"{{ sap_secondary_instance }}"
    -inf: "{{ sap_secondary_instance }}"

# TODO: include application-specific tasks based on sap_application variable (e.g. hana, netweaver).
# - include_tasks: 'resource-{{ sap_application }}-{{ ansible_os_family | lower }}.yml'

- name: check maintenance mode
  command: crm configure get_property maintenance-mode
  register: maintenance_mode_status
  changed_when: false

- name: disable maintenance mode
  command: crm configure property maintenance-mode=false
  when: |
    maintenance_mode_status.stdout == 'true'
