---
- block:
  - name: create cloned sap hana topology resource
    command: >-
      pcs resource create SAPHanaTopology_{{ sap_hana_sid }}_{{ sap_hana_instance_number }}
      SAPHanaTopology SID={{ sap_hana_sid }}
      InstanceNumber={{ sap_hana_instance_number }}
      op start timeout=600
      op stop timeout=300
      op monitor interval=10 timeout=600
      clone clone-max=2 clone-node-max=1 interleave=true

  - name: create master and slave sap hana resource
    command: >-
      pcs resource create SAPHana_{{ sap_hana_sid }}_{{ sap_hana_instance_number }}
      SAPHana SID={{ sap_hana_sid }}
      InstanceNumber={{ sap_hana_instance_number }}
      PREFER_SITE_TAKEOVER=true DUPLICATE_PRIMARY_TIMEOUT=7200 AUTOMATED_REGISTER=true
      op start timeout=3600
      op stop timeout=3600
      op monitor interval=61 role=Slave timeout=700
      op monitor interval=59 role=Master timeout=700
      op promote timeout=3600
      op demote timeout=3600
      master meta notify=true clone-max=2 clone-node-max=1 interleave=true

  - name: create start order constraint
    command: >-
      pcs constraint order SAPHanaTopology_{{ sap_hana_sid }}_{{ sap_hana_instance_number }}-clone
      then SAPHana_{{ sap_hana_sid }}_{{ sap_hana_instance_number }}-master symmetrical=false

  - name: create colocation constraint
    command: >-
      pcs constraint colocation add {{ sap_vip_resource }} with master
      SAPHana_{{ sap_hana_sid }}_{{ sap_hana_instance_number }}-master 2000

  - name: create vip group constraint
    command: >-
      pcs constraint colocation add g-primary with master
      SAPHana_{{ sap_hana_sid }}_{{ sap_hana_instance_number }}-master 2000
  when:
    ansible_os_family == 'RedHat'

- block:
  - name: create sap hana topology resource
    command: >-
      crm configure primitive rsc_SAPHanaTopology_{{ sap_hana_sid }}_{{ sap_hana_instance_number }}
      ocf:suse:SAPHanaTopology
      operations \$id=rsc_sap2_{{ sap_hana_sid }}_{{ sap_hana_instance_number }}-operations
      op monitor interval=10 timeout=600
      op start interval=0 timeout=600
      op stop interval=0 timeout=300
      params SID={{ sap_hana_sid }} InstanceNumber={{ sap_hana_instance_number }}
    register: crm_command_status
    changed_when: crm_command_status.rc == 0
    failed_when: |
      'Found existing primitive with same ID' not in crm_command_status.stderr and crm_command_status.rc != 0

  - name: clone the sap hana topology resource
    command: >-
      crm configure clone cln_SAPHanaTopology_{{ sap_hana_sid }}_{{ sap_hana_instance_number }}
      rsc_SAPHanaTopology_{{ sap_hana_sid }}_{{ sap_hana_instance_number }}
      meta is-managed=true clone-node-max=1 target-role=Started interleave=true
    register: crm_command_status
    changed_when: crm_command_status.rc == 0
    failed_when: |
      'Found existing clone with same ID' not in crm_command_status.stderr and crm_command_status.rc != 0

  - name: create sap hana resource
    command: >-
      crm configure primitive rsc_SAPHana_{{ sap_hana_sid }}_{{ sap_hana_instance_number }}
      ocf:suse:SAPHana
      operations \$id=rsc_sap_{{ sap_hana_sid }}_{{ sap_hana_instance_number }}-operations
      op start interval=0 timeout=3600
      op stop interval=0 timeout=3600
      op promote interval=0 timeout=3600
      op monitor interval=10 role=Master timeout=700
      op monitor interval=11 role=Slave timeout=700
      params SID={{ sap_hana_sid }} InstanceNumber={{ sap_hana_instance_number }}
      PREFER_SITE_TAKEOVER=true DUPLICATE_PRIMARY_TIMEOUT=7200 AUTOMATED_REGISTER=true
    register: crm_command_status
    changed_when: crm_command_status.rc == 0
    failed_when: |
      'Found existing primitive with same ID' not in crm_command_status.stderr and crm_command_status.rc != 0
     
  - name: create master and slave sap hana resource
    command: >-
      crm configure ms msl_SAPHana_{{ sap_hana_sid }}_{{ sap_hana_instance_number }}
      rsc_SAPHana_{{ sap_hana_sid }}_{{ sap_hana_instance_number }}
      meta is-managed=true notify=true clone-max=2 clone-node-max=1
      target-role=Started interleave=true
    register: crm_command_status
    changed_when: crm_command_status.rc == 0
    failed_when: |
      'Found existing ms with same ID' not in crm_command_status.stderr and crm_command_status.rc != 0

  - name: create colocation constraint
    command: >-
      crm configure colocation col_saphana_ip_{{ sap_hana_sid }}_{{ sap_hana_instance_number }}
      4000: g-primary:Started msl_SAPHana_{{ sap_hana_sid }}_{{ sap_hana_instance_number }}:Master
    register: crm_command_status
    changed_when: crm_command_status.rc == 0
    failed_when: |
      'Found existing colocation with same ID' not in crm_command_status.stderr and crm_command_status.rc != 0
     
  - name: create start order constraint
    command: >-
      crm configure order ord_SAPHana_{{ sap_hana_sid }}_{{ sap_hana_instance_number }}
      Optional: cln_SAPHanaTopology_{{ sap_hana_sid }}_{{ sap_hana_instance_number }}
      msl_SAPHana_{{ sap_hana_sid }}_{{ sap_hana_instance_number }}
    register: crm_command_status
    changed_when: crm_command_status.rc == 0
    failed_when: |
      'Found existing order with same ID' not in crm_command_status.stderr and crm_command_status.rc != 0
  when:
    ansible_os_family == 'Suse'
