---
- name: write cluster configuration
  command: >-
    pcs cluster setup --name hana --local --force
    {{ sap_primary_instance }} {{ sap_secondary_instance }}
  args:
    creates: /etc/corosync/corosync.conf

- name: start and enable services
  service:
    name: '{{ item }}'
    state: started
    enabled: true
  loop:
  - pacemaker.service
  - pcsd.service
