---
- name: configure csync2
  command: ha-cluster-join -y -c {{ sap_primary_instance_ip }} csync2
  args:
    creates: /etc/corosync/corosync.conf
  when: not is_primary

- name: start and enable services
  service:
    name: '{{ item }}'
    state: started
    enabled: true
  loop:
  - corosync.service
  - hawk.service
  - pacemaker.service
  when: not is_primary
