---
- block:
  - command: pcs property show maintenance-mode
    register: maintenance_mode_status
    changed_when: false

  - name: enable maintenance mode
    command: pcs property set maintenance-mode=true
    when: >-
      'maintenance-mode' not in maintenance_mode_status.stdout or
      'maintenance-mode: false' in maintenance_mode_status.stdout
  when: |
    ansible_os_family == 'RedHat'

- block:
  - command: crm configure get_property maintenance-mode
    register: maintenance_mode_status
    changed_when: false

  - name: enable maintenance mode
    command: crm configure property maintenance-mode=true
    when: |
      maintenance_mode_status.stdout == 'false'
  when: |
    ansible_os_family == 'Suse'
