---
- name: deleting the line from /sapmnt/sidid/profile/SL2_ERS_gcpsapers
  lineinfile:
    path: /sapmnt/{{ ascs_sid }}/profile/{{ ascs_sid }}_ERS{{ sap_deployment_ers_instance_nr }}_{{ sap_deployment_ersVirtualHostname }}
    line: "{{ item }}"
    state: absent
  with_items:
    - 'Restart_Program_00 = local $(_ER) pf=$(_PFL) NR=$(SCSID)'
    - 'Autostart = 1'
#    with_items:
#      - 'Restart_Program_01 = local $(_EN) pf=$(_PF)'
- name: Adding line from /sapmnt/sidid/profile/SL2_ERS_gcpsapers
  lineinfile:
    path: /sapmnt/{{ ascs_sid }}/profile/{{ ascs_sid }}_ERS{{ sap_deployment_ers_instance_nr }}_{{ sap_deployment_ersVirtualHostname }}
    line: "{{ item }}"
    state: present
  with_items:
    - 'Start_Program_00 = local $(_ER) pf=$(_PFL) NR=$(SCSID)'
    - 'service/halib = $(DIR_CT_RUN)/saphascriptco.so'
    - 'service/halib_cluster_connector = /usr/bin/sap_suse_cluster_connector'

- name: Adding line from /usr/sap/sapservices
  lineinfile:
    path: /usr/sap/sapservices
    line: "{{ item }}"
    state: present
  with_items:
    - 'LD_LIBRARY_PATH=/usr/sap/{{ ascs_sid }}/ASCS{{ sap_deployment_ascs_instance_nr }}/exe:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; /usr/sap/{{ ascs_sid }}/ASCS{{ sap_deployment_ascs_instance_nr }}/exe/sapstartsrv pf=/usr/sap/{{ ascs_sid }}/SYS/profile/{{ ascs_sid }}_ASCS{{ sap_deployment_ascs_instance_nr }}_{{ sap_deployment_ascsVirtualHostname }} -D -u {{ sap_nw_user }}adm'
