# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: define profile for ascs
  set_fact:
    sap_profile: /sapmnt/{{ sap_nw_sid }}/profile/{{ sap_nw_sid }}_ASCS{{ sap_nw_ascs_instance_number }}_{{ sap_nw_ascs_virtual_host }}
  when: ansible_default_ipv4.address in groups.ascs

- name: define profile for ers
  set_fact:
    sap_profile: /sapmnt/{{ sap_nw_sid }}/profile/{{ sap_nw_sid }}_ERS{{ sap_nw_ers_instance_number }}_{{ sap_nw_ers_virtual_host }}
  when: ansible_default_ipv4.address in groups.ers

- name: modify profile and sapservices for ascs
  lineinfile:
    path: '{{ item.path }}'
    regex: "{{ item.regex | default(omit) }}"
    backrefs: '{{ "regex" in item }}'
    line: "{{ item.line | default(omit) }}"
    state: '{{ item.state }}'
  with_items:
  # Change Restart_Program_01 to Start_Program_01 for HA, as pacemaker should manage restarts.
  - path: '{{ sap_profile }}'
    regex: '^Res(tart_Program_01 .*$)'
    line: 'S\1'
    state: present
  - path: '{{ sap_profile }}'
    line: 'enque/encni/set_so_keepalive = true'
    state: '{{ "present" if sap_ensa_version == "1" else "absent" }}'
  - path: /usr/sap/sapservices
    line: 'LD_LIBRARY_PATH=/usr/sap/{{ sap_nw_sid }}/ERS{{ sap_nw_ers_instance_number }}/exe:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; /usr/sap/{{ sap_nw_sid }}/ERS{{ sap_nw_ers_instance_number }}/exe/sapstartsrv pf=/usr/sap/{{ sap_nw_sid }}/ERS{{ sap_nw_ers_instance_number }}/profile/{{ sap_nw_sid }}_ERS{{ sap_nw_ers_instance_number }}_{{ sap_nw_ers_virtual_host }} -D -u {{ sap_nw_user }}'
    state: present
  when: ansible_default_ipv4.address in groups.ascs

- name: modify profile and sapservices for ers
  lineinfile:
    path: '{{ item.path }}'
    regex: "{{ item.regex | default(omit) }}"
    backrefs: '{{ "regex" in item }}'
    line: "{{ item.line | default(omit) }}"
    state: '{{ item.state }}'
  with_items:
  # Change Restart_Program_00 to Start_Program_00 for HA, as pacemaker should manage restarts.
  - path: '{{ sap_profile }}'
    regex: '^Res(tart_Program_00 .*$)'
    line: 'S\1'
    state: present
  - path: '{{ sap_profile }}'
    line: 'Autostart = 1'
    state: absent
  - path: /usr/sap/sapservices
    line: 'LD_LIBRARY_PATH=/usr/sap/{{ sap_nw_sid }}/ASCS{{ sap_nw_ascs_instance_number }}/exe:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; /usr/sap/{{ sap_nw_sid }}/ASCS{{ sap_nw_ascs_instance_number }}/exe/sapstartsrv pf=/usr/sap/{{ sap_nw_sid }}/SYS/profile/{{ sap_nw_sid }}_ASCS{{ sap_nw_ascs_instance_number }}_{{ sap_nw_ascs_virtual_host }} -D -u {{ sap_nw_user }}'
    state: present
  when: ansible_default_ipv4.address in groups.ers

- name: modify profile to enable sap suse cluster connector
  lineinfile:
    path: '{{ item.path }}'
    regex: "{{ item.regex | default(omit) }}"
    backrefs: '{{ "regex" in item }}'
    line: "{{ item.line | default(omit) }}"
    state: '{{ item.state }}'
  with_items:
  - path: '{{ sap_profile }}'
    line: 'service/halib = $(DIR_CT_RUN)/saphascriptco.so'
    state: present
  - path: '{{ sap_profile }}'
    line: 'service/halib_cluster_connector = /usr/bin/sap_suse_cluster_connector'
    state: present
  when: ansible_os_family == 'Suse'

- name: add sidadm to haclient group for sap suse cluster connector
  user:
    name: '{{ sap_nw_user }}'
    groups: haclient
    append: true
  when: ansible_os_family == 'Suse'
