---
- name: selecting ASCS machines
  set_fact:
    is_ascs: '{{ ansible_default_ipv4.address in terraform.outputs.inventory.value["ascs"] }}'
- name: include ASCS Tasks
  include_tasks: '{{ role_path }}/tasks/ascs.yml'
  when: is_ascs
- name: selecting ERS machines
  set_fact:
    is_ers: '{{ ansible_default_ipv4.address in terraform.outputs.inventory.value["ers"] }}'
- name: include ERS Tasks
  include_tasks: '{{ role_path }}/tasks/ers.yml'
  when: is_ers
