---
- name: include base primary tasks
  include_role:
    name: base
- name: include storage primary tasks
  include_role:
    name: storage-bkup
  vars:
    swapon: True
    subnet_cidr: '{{ terraform.outputs.subnet_cidr.value }}'
    disks:
      - { name: usrsap, partition_path : usrsap }
      - { name: swap, partition_path : swap }
    logvols:
      usrsap:
        size: "{{ sap_nw_usrsap_disk_size }}G"
        vol: usrsap
        mountpoint: /usr/sap
    swapvols:
      swap:
        size: "{{ sap_nw_swap_disk_size }}G"
        vol: swap
        mountpoint: /swap
- name: include storage primary tasks
  include_role:
    name: storage-bkup
    tasks_from: ha
  vars:
    nfsvols: "{{ sap_nw_nfsvols }}"
- name: include nw-pre primary tasks
  include_role:
    name: nw-pre
  vars:
    nw_bucket: "{{ sap_nw_install_files_bucket }}"
    folder: "{{ sap_nw_install_files_bucket_prefix }}"
    storage: "{{ sap_nw_storage_files }}"
    cloudsdk_python_export_path: "{{ sap_nw_cloudsdk_python_export_path }}"
- name: include nw primary tasks
  include_role:
    name: ascs
    tasks_from: ha
  vars:
    sap_nw_product_id: "{{ sap_nw_ascs_product_id }}"
    sap_nw_ascs_sid: "{{ sap_nw_sid }}"
- name: include storage primary tasks
  include_role:
    name: post-deploy
  vars:
    sap_nw_ascs_sid: "{{ sap_nw_sid }}" 
