---
- name: include base primary tasks
  include_role:
    name: base
- name: include storage primary tasks
  include_role:
    name: storage-bkup
  vars:
    swapon: True
    subnet_cidr: '{{ terraform.outputs.subnet_cidr.value }}'
    disks:
      - { name: usrsap, partition_path : usrsap }
      - { name: swap, partition_path : swap }
    logvols:
      usrsap:
        size: "{{ sap_nw_usrsap_disk_size }}G"
        vol: usrsap
        mountpoint: /usr/sap
    swapvols:
      swap:
        size: "{{ sap_nw_swap_disk_size }}G"
        vol: swap
        mountpoint: /swap
- name: include storage primary tasks
  include_role:
    name: storage-bkup
    tasks_from: ha
- name: include nw primary tasks
  include_role:
    name: user
  vars:
    sap_nw_product_id: "{{ sap_nw_user_product_id }}"
- name: include nw primary tasks
  include_role:
    name: ers
  vars:
    sap_use_alias: true 
    sap_nw_product_id: "{{ sap_nw_ers_product_id }}"
- name: include storage primary tasks
  include_role:
    name: post-deploy
  vars:
    sap_nw_ascs_sid: "{{ sap_nw_sid }}"
