---

- name: Create .deploy directory
  file:
    path: /root/.deploy
    state: directory
    mode: '0755'

- name: Create cfg file for master
  template:
    src: "{{ role_path }}/templates/configfile.j2"
    dest: "/root/.deploy/hana_passwords.xml"
  register: hana_passwords_xml

- name: Add worker nodes to master
  shell: |
    cat /root/.deploy/hana_passwords.xml | ./hdblcm --action=add_hosts --addhosts={{ item.split('/')[10] }} --root_user=root --listen_interface=global --read_password_from_stdin=xml -b
  args:
    chdir: "{{ sap_hana_shared_mountpoint }}/{{ sap_hana_sid }}/hdblcm/"
    creates: "/usr/sap/{{ sap_hana_sid }}/SYS/profile/{{ sap_hana_sid }}_HDB{{ sap_hana_instance_number }}_{{ item.split('/')[10] }}"
  with_items:
    - "{{ sap_hana_worker_node_names }}"