---
sap_gcloud_path: /usr/bin/gcloud
sap_cluster_name: hacluster
sap_cluster_user: hacluster
sap_cluster_user_password: linux
sap_cluster_instance_number: '00'
sap_use_lb: true
sap_health_check_port: 60000
