---
- name: mount path creation for NFS
  file:
    path: "{{ item.value }}"
    state: directory
  with_dict: "{{ nfsvols }}"
- name: Mount and make fstab entries for NFS
  mount:
    path: "{{ item.value }}"
    fstype: "nfs"
    src: "{{ item.key }}"
    state: mounted
  with_dict: "{{ nfsvols }}"
  tags:
    - disk_setup
  when: nfsvols is defined
- name: add a list of VIP to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item['ip'] }}.*$"
    line: "{{ item['ip'] }}\t\t{{ item['names'] | join(' ') }}"
    state: present
  with_items:
  - ip: "{{ sap_nw_ascs_ilb_ip }}"
    names:
    - "{{ sap_nw_ascs_dns }}"
    - "{{ sap_nw_ascs_virtual_host }}"
  - ip: "{{ sap_nw_ers_ilb_ip }}"
    names:
    - "{{ sap_nw_ers_dns }}"
    - "{{ sap_nw_ers_virtual_host }}"
