---
- name: read /etc/fstab
  slurp:
    path: /etc/fstab
  register: etc_fstab_file
  changed_when: false
  when: sap_nw_create_nfs_source_dirs

- block:
  - name: mount NFS share
    mount:
      fstab: /tmp/fstab
      fstype: nfs
      path: /mnt
      src: "{{ nfs_src }}"
      state: mounted
  - name: make directories on NFS share
    file:
      path: "/mnt/{{ sap_nw_sid }}/{{ item.key }}"
      mode: 0755
      state: directory
    with_dict: "{{ nfsvols }}"
  always:
  - name: unmount NFS share
    mount:
      fstab: /tmp/fstab
      fstype: nfs
      path: /mnt
      src: "{{ nfs_src }}"
      state: unmounted
  - name: remove temporary fstab
    file:
      path: /tmp/fstab
      state: absent
  when: |
    sap_nw_create_nfs_source_dirs and nfs_src not in etc_fstab_file.content | b64decode

- name: mount path creation for NFS
  file:
    path: "{{ item.value }}"
    state: directory
  with_dict: "{{ nfsvols }}"
- name: Mount and make fstab entries for NFS
  mount:
    path: "{{ item.value }}"
    fstype: "nfs"
    src: "{{ item.key }}"
    state: mounted
  with_dict: "{{ nfsvols }}"
  tags:
    - disk_setup
  when: nfsvols is defined
- name: add a list of VIP to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ item['ip'] }}.*$"
    line: "{{ item['ip'] }}\t\t{{ item['names'] | join(' ') }}"
    state: present
  with_items:
  - ip: "{{ sap_nw_ascs_vip }}"
    names:
    - "{{ sap_nw_ascs_virtual_host }}.{{ sap_domain }}"
    - "{{ sap_nw_ascs_virtual_host }}"
  - ip: "{{ sap_nw_ers_vip }}"
    names:
    - "{{ sap_nw_ers_virtual_host }}.{{ sap_domain }}"
    - "{{ sap_nw_ers_virtual_host }}"
  - ip: "{{ sap_hana_vip }}"
    names:
    - "{{ sap_hana_virtual_host }}.{{ sap_domain }}"
    - "{{ sap_hana_virtual_host }}"
