---
- name: permissions to home
  file:
    path: /usr/sap
    state: directory
    mode: 0777
    recurse: true

- name: changing permissions
  file:
    path: /sapmnt
    state: directory
    mode: 0777
    recurse: true
    
- name: create ers-alias-ip resource
  command: >-
     ip addr add {{ sap_nw_ers_vip }} dev eth0
  when: sap_use_alias is defined and ansible_os_family == 'RedHat'    
  register: ers_alias_ip
  changed_when: ers_alias_ip.rc == 0
  failed_when: 'ers_alias_ip.rc !=0 and "RTNETLINK answers: File exists" not in ers_alias_ip.stderr'

- name: inifile.params config file
  template:
    src: "{{ sap_nw_ini_template }}"
    dest: /usr/sap/inifile_ers.params

- name: check for files created by ers installer
  stat:
    path: '{{ item }}'
  loop:
  - '/usr/sap/{{ sap_nw_sid }}/ERS{{ sap_nw_ers_instance_number }}/exe/sapcontrol'
  - '/usr/sap/hostctrl/exe/saphostexec'
  register: ers_installed_files

- name: installing s4-hana
  command: >-
     ./sapinst SAPINST_INPUT_PARAMETERS_URL=/usr/sap/inifile_ers.params \
     SAPINST_EXECUTE_PRODUCT_ID={{ sap_nw_product_id }} \
     SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false
  args:
   chdir: "{{ sap_product_vars[sap_product_and_version].sap_nw_sapcar_path }}"
  when: false in ers_installed_files.results | map(attribute="stat") | map(attribute="exists") | list
