- name: define instances
  set_fact:
    _sap_instances: '{{ item }}, {{ sap_hana_instance_number | int }}, 5{{ sap_hana_instance_number }}13, 5{{ sap_hana_instance_number }}14, 0.3, HDB|HDB_WORKER, GREEN'
  register: sap_instances_fact
  loop: '{{ sap_hana_instances }}'

- name: include sap assertions role for master
  include_role:
    name: sap-assertions
  vars:
    sap_become_user: '{{ sap_hana_user }}'
    sap_expected_processes:
    - hdbdaemon, HDB Daemon, GREEN, Running
    - hdbcompileserver, HDB Compileserver, GREEN, Running
    - hdbindexserver, HDB Indexserver-{{ sap_hana_sid }}, GREEN, Running
    - hdbnameserver, HDB Nameserver, GREEN, Running
    - hdbpreprocessor, HDB Preprocessor, GREEN, Running
    - hdbwebdispatcher, HDB Web Dispatcher, GREEN, Running
    - hdbxsengine, HDB XSEngine-{{ sap_hana_sid }}, GREEN, Running
    sap_instances: '{{ sap_instances_fact.results | map(attribute="ansible_facts._sap_instances") | list }}'
    sap_instance_number: '{{ sap_hana_instance_number }}'
  when: ansible_hostname == sap_hana_master_instance_name

- name: include sap assertions role for workers
  include_role:
    name: sap-assertions
  vars:
    sap_become_user: '{{ sap_hana_user }}'
    sap_expected_processes:
    - hdbdaemon, HDB Daemon, GREEN, Running
    - hdbcompileserver, HDB Compileserver, GREEN, Running
    - hdbindexserver, HDB Indexserver-{{ sap_hana_sid }}, GREEN, Running
    - hdbnameserver, HDB Nameserver, GREEN, Running
    - hdbpreprocessor, HDB Preprocessor, GREEN, Running
    - hdbwebdispatcher, HDB Web Dispatcher, GREEN, Running
    sap_instances: '{{ sap_instances_fact.results | map(attribute="ansible_facts._sap_instances") | list }}'
    sap_instance_number: '{{ sap_hana_instance_number }}'
  when: ansible_hostname != sap_hana_master_instance_name
