---

- name: Include base role
  include_role:
    name: base
  when: not ( ansible_hostname | regex_search('([w]\d\d+$)') ) and ( sap_add_worker_nodes is not defined )

- name: Include storage role
  include_role:
    name: storage
  vars:
    disks: "{{ sap_hana_disks }}"
    logvols: "{{ sap_hana_logvols }}"
    swapon: "{{ sap_hana_swapon | default(false) }}"
  when: not ( ansible_hostname | regex_search('([w]\d\d+$)') ) and ( sap_add_worker_nodes is not defined )

- name: Include hana packages download role
  include_role:
    name: sap-hana-download-packages
  when: not ( ansible_hostname | regex_search('([w]\d\d+$)') ) and ( sap_add_worker_nodes is not defined )

- name: Include sap preconfigure agent role
  include_role:
    name: sap-preconfigure
  when: ( ansible_os_family == "RedHat") and not ( ansible_hostname | regex_search('([w]\d\d+$)') )

- name: Include sap hana preconfigure agent role
  include_role:
    name: sap-hana-preconfigure
  when: ( ansible_os_family == "RedHat") and (not ( ansible_hostname | regex_search('([w]\d\d+$)') ))

- name: Include sap hana install role
  include_role:
    name: sap-hana-install
  when: not ( ansible_hostname | regex_search('([w]\d\d+$)') ) and ( sap_add_worker_nodes is not defined )

- name: Include sap hana nfs config role
  include_role:
    name: sap-hana-config-nfs
  when: not ( ansible_hostname | regex_search('([w]\d\d+$)') ) and ( sap_add_worker_nodes is not defined )

- name: Include sap ssh keygen role
  include_role:
    name: ssh-keygen
  when: not ( ansible_hostname | regex_search('([w]\d\d+$)') ) and ( sap_add_worker_nodes is not defined )

- name: Include sap parameters set role
  include_role:
    name: sap-hana-set-parameters
  when: not ( ansible_hostname | regex_search('([w]\d\d+$)') ) and ( sap_add_worker_nodes is not defined )

- name: Include sap hana start role
  include_role:
    name: sap-hana-start
  when: not ( ansible_hostname | regex_search('([w]\d\d+$)') ) and ( sap_add_worker_nodes is not defined )

- name: Include sap host agent role
  include_role:
    name: sap-hostagent
  when: not ( ansible_hostname | regex_search('([w]\d\d+$)') ) and ( sap_add_worker_nodes is not defined )

- name: Include common role
  include_role:
    name: common
  when: ansible_hostname | regex_search('([w]\d\d+$)')

- name: Include copy ssh keys role
  include_role:
    name: sap-hana-copy-ssh-keys
  when: ansible_hostname | regex_search('([w]\d\d+$)')

- name: Include worker storage role
  include_role:
    name: storage
  vars:
    disks: "{{ sap_hana_disks }}"
    logvols: "{{ sap_hana_logvols }}"
    swapon: "{{ sap_hana_swapon | default(false) }}"
  when: ansible_hostname | regex_search('([w]\d\d+$)')

- name: Include sap hana mount role
  include_role:
    name: sap-hana-mount-nfs
  when: ansible_hostname | regex_search('([w]\d\d+$)')

- name: Include sap hana worker node add role
  include_role:
    name: sap-hana-add-worker-nodes
  when: not ( ansible_hostname | regex_search('([w]\d\d+$)') ) and ( sap_add_worker_nodes is defined )

- name: Include sap hana stop role
  include_role:
    name: sap-hana-stop
  when: not ( ansible_hostname | regex_search('([w]\d\d+$)') ) and ( sap_add_worker_nodes is defined )

- name: Include sap hana start role
  include_role:
    name: sap-hana-start
  when: not ( ansible_hostname | regex_search('([w]\d\d+$)') ) and ( sap_add_worker_nodes is defined )