---

- name: Set auto hana start
  shell: |
    sudo sed -i -e 's/Autostart = 0/Autostart = 1/g' /usr/sap/BG1/SYS/profile/*

- name: Stop Hana
  include_role:
    name: sap-hana-stop

- name: Start Hana
  include_role:
    name: sap-hana-start

- name: Run failover config
  shell: |
    echo "call SYS.UPDATE_LANDSCAPE_CONFIGURATION('deploy','{\"HOSTS\":{\"bghanasbw01\":{\"WORKER_CONFIG_GROUPS\":\"default\",\"FAILOVER_CONFIG_GROUP\":\"default\",\"INDEXSERVER_CONFIG_ROLE\":\"WORKER\",\"NAMESERVER_CONFIG_ROLE\":\"MASTER 2\"},\"bghanasbw0{{ sap_instance_count_worker|int + 1 }}\":{\"WORKER_CONFIG_GROUPS\":\"default\",\"FAILOVER_CONFIG_GROUP\":\"default\",\"INDEXSERVER_CONFIG_ROLE\":\"STANDBY\",\"NAMESERVER_CONFIG_ROLE\":\"MASTER 3\"}}}')" > /root/.deploy/hdbconfig.sql
    source /usr/sap/{{ sap_hana_sid }}/home/.sapenv.sh && hdbsql -d SYSTEMDB -u SYSTEM -p Google123 -i 00 -I /root/.deploy/hdbconfig.sql -O /dev/null
    source /usr/sap/{{ sap_hana_sid }}/home/.sapenv.sh && hdbsql -u SYSTEM -p Google123 -i 00 -I /root/.deploy/hdbconfig.sql -O /dev/null

- name: Add a line to a file if the file does not exist, without passing regexp
  lineinfile:
    path: /hana/shared/gceStorageClient/global.ini
    line: partition_*_*__fencing = disabled
    state: absent

- name: Add a line to a file if the file does not exist, without passing regexp
  lineinfile:
    path: /hana/shared/gceStorageClient/global.ini
    insertafter: '^\[storage\]'
    line: partition_*_*__fencing = enabled
    create: yes
