---

- name: Ensure pip is installed.
  package:
    name: python2-pip
    state: present
  register: pip_installed

- name: Install required python package from GCE storage client
  pip:
    name: pyasn1-modules

- name: Create gcloud directory under sidadm user home directory
  file:
    path: '{{ sap_hana_usr_mountpoint }}/{{ sap_hana_sid }}/home/.config/gcloud/'
    state: directory
    owner: '{{ sap_hana_system_uid }}'
    group: '{{ sap_sapsys_gid }}'
    recurse: true

- name: Updating /etc/sudoers
  lineinfile:
    path: /etc/sudoers
    line: '{{ item }}'
  with_items:
    - '{{ sap_hana_user }} ALL=NOPASSWD: /sbin/multipath,/sbin/multipathd,/etc/init.d/multipathd,/usr/bin/sg_persist,/bin/mount,/bin/umount,/bin/kill,/usr/bin/lsof,/usr/bin/systemctl,/usr/sbin/lsof,/usr/sbin/xfs_repair,/usr/bin/mkdir,/sbin/vgscan,/sbin/pvscan,/sbin/lvscan,/sbin/vgchange,/sbin/lvdisplay,/usr/bin/gcloud'
    - ''

## Keep this temp to over come perms issues when installing Hana
- name: 'Create {{ sap_hana_data_mountpoint }} and {{ sap_hana_log_mountpoint }}'
  file:
    path: '{{ item }}'
    state: directory
    recurse: true
    mode: 0777
  with_items:
    - '{{ sap_hana_data_mountpoint }}'
    - '{{ sap_hana_log_mountpoint }}'