---
- name: permissions to home 
  file:
    path: /usr/sap
    state: directory
    mode: 0777
    recurse: true

- name: changing permissions
  file:
    path: /sapmnt
    state: directory
    mode: 0777
    recurse: true

- name: Setting fact for nw installer path
  set_fact:
    sapinst_path: "{{ sap_deployment_sapcar_path }}"

- name: inifile.params config file 
  template:
    src: "{{ template }}"
    dest: /usr/sap/inifile_nw.params
    
- name: installing s4-hana 
  command: >- 
     ./sapinst SAPINST_INPUT_PARAMETERS_URL=/usr/sap/inifile_nw.params \
     SAPINST_EXECUTE_PRODUCT_ID={{ sap_deployment_product_id }} \
     SAPINST_SKIP_DIALOGS=true SAPINST_START_GUISERVER=false
  register: installnw
  args:
   chdir: "{{ sapinst_path }}"
  when: true
- debug:
   var: installs4hana
