---

- name: Include base role
  include_role:
    name: base

- name: Include storage role
  include_role:
    name: storage
  vars:
    disks: "{{ sap_hana_disks }}"
    logvols: "{{ sap_hana_logvols }}"
    swapon: "{{ sap_hana_swapon | default(false) }}"

- name: Include hana packages download role
  include_role:
    name: sap-hana-download-packages

- name: Include sap pre-configure role
  include_role:
    name: sap-preconfigure
  when: ansible_os_family == "RedHat"

- name: Include sap hana pre-configure role
  include_role:
    name: sap-hana-preconfigure
  when: ansible_os_family == "RedHat"

- name: Include sap hana install role
  include_role:
    name: sap-hana-install

- name: Include sap hana start role
  include_role:
    name: sap-hana-start

- name: Include SAP hostagent install role
  include_role:
    name: sap-hostagent

- name: Include sap hana ssfs copy keys role
  include_role:
    name: sap-hana-ssfs-keys

- name: Include sap hana backup config role
  include_role:
    name: sap-hana-config-backup

- name: Include sap hana hdb user create role
  include_role:
    name: sap-hana-hdb-user

- name: Include sap hana hdb userstore role
  include_role:
    name: sap-hana-hdb-userstore

- name: Include sap hana backup role
  include_role:
    name: sap-hana-backup

- name: Include sap hana hsr config role
  include_role:
    name: sap-hana-hsr

- name: Include pacemaker install/config role
  include_role:
    name: pacemaker-hana

- name: Include SAP hana backint role
  include_role:
    name: sap-hana-backint
  when: sap_hana_backint_install|bool == true
