---

- name: SAP HANA deploy
  hosts: 127.0.0.1
  connection: local
  roles:
  - role: forminator
    vars:
      sap_tf_state_bucket: '{{ sap_hana_state_bucket }}'
      sap_tf_state_bucket_prefix: '{{ sap_hana_instance_name }}'
      sap_tf_project_path: ./tf
      sap_state: '{{ state | default("present") }}'
      sap_tf_variables:
        boot_disk_size: '{{ sap_hana_boot_disk_size }}'
        instance_name: '{{ sap_hana_instance_name }}'
        instance_type: '{{ sap_hana_instance_type }}'
        source_image_family: '{{ sap_hana_source_image_family }}'
        source_image_project: '{{ sap_hana_source_image_project }}'
        region: '{{ sap_hana_region }}'
        zone_a: '{{ sap_hana_zone_a }}'
        zone_b: '{{ sap_hana_zone_b }}'
        service_account_email: '{{ sap_hana_service_account_email }}'
        subnetwork: '{{ sap_hana_subnetwork }}'
        subnetwork_project: '{{ sap_hana_subnetwork_project_id | default("") }}'
        sap_install_files_bucket: '{{ sap_install_files_bucket }}'
        sap_hostagent_file_name: '{{ sap_hostagent_file_name }}'
        sap_hana_bundle_file_name: '{{ sap_hana_bundle_file_name }}'
        sap_hana_sapcar_file_name: '{{ sap_hana_sapcar_file_name }}'
        run_provisioner: 'false'

- name: SAP HANA configure on both primay and secondary
  hosts: hana
  become: yes
  vars:
    sap_image_family: '{{ terraform.outputs.sap_image_family.value }}'
    sap_hana_deployment_hostagent_file_name: '{{ terraform.outputs.sap_hostagent_file_name.value }}'
    sap_hana_deployment_bundle_sar_file_name: '{{ terraform.outputs.sap_hana_bundle_file_name.value }}'
    sap_hana_deployment_sapcar_file_name: '{{ terraform.outputs.sap_hana_sapcar_file_name.value }}'
    sap_hana_primary_instance_name: '{{ terraform.outputs.primary_instance_name.value }}'
    sap_hana_secondary_instance_name: '{{ terraform.outputs.secondary_instance_name.value }}'
    sap_hana_primary_instance_ip: '{{ terraform.outputs.primary_instance_ip.value }}'
    sap_hana_secondary_instance_ip: '{{ terraform.outputs.secondary_instance_ip.value }}'
    sap_hana_primary_instance_zone: '{{ terraform.outputs.zone_a.value }}'
    sap_hana_secondary_instance_zone: '{{ terraform.outputs.zone_b.value }}'
    sap_hana_ilb_ip: '{{ terraform.outputs.hana_ilb_ip.value }}'
    sap_hana_project_id: '{{ terraform.outputs.project_id.value }}'
    sap_hana_health_check_port: '{{ terraform.outputs.health_check_port.value }}'
    sap_hostagent_rpm_file_name: '{{ terraform.outputs.sap_hostagent_file_name.value }}'
    hana_shared_size: '{{ terraform.outputs.hana_shared_size.value }}G'
    hana_data_size: '{{ terraform.outputs.hana_data_size.value }}G'
    hana_log_size: '{{ terraform.outputs.hana_log_size.value }}G'
    hana_usr_size: '{{ terraform.outputs.hana_usr_size.value }}G'
    hana_backup_size: '{{ terraform.outputs.hana_backup_size.value - 1 }}G'
    swapon: false
    disks:
        - { name: data, partition_path : "{{ sap_hana_data_partition_name }}"}
        - { name: backup, partition_path : "{{ sap_hana_backup_partition_name }}"}
    logvols:
      shared:
        size: "{{ hana_shared_size }}"
        vol: "{{ sap_hana_data_partition_name }}" 
        mountpoint: "{{ sap_hana_shared_mountpoint }}"
        fstype: xfs
      data:
        size: "{{ hana_data_size }}"
        vol: "{{ sap_hana_data_partition_name }}"
        mountpoint: "{{ sap_hana_data_mountpoint }}"
        fstype: xfs
      log:
        size: "{{ hana_log_size }}"
        vol: "{{ sap_hana_data_partition_name }}"
        mountpoint: "{{ sap_hana_log_mountpoint }}"
        fstype: xfs
      usr:
        size: "{{ hana_usr_size }}"
        vol: "{{ sap_hana_data_partition_name }}"
        mountpoint: "{{ sap_hana_usr_mountpoint }}"
        fstype: xfs
      backup:
        size: "{{ hana_backup_size}}"
        vol: "{{ sap_hana_backup_partition_name }}"
        mountpoint: "{{ sap_hana_backup_mountpoint }}"
        fstype: xfs
  roles:
  - role: sap-hana-ha-role
