---
- name: check if ssh key files are present
  stat:
    path: '{{ item }}'
  loop:
  - '{{ sap_gce_ssh_priv_key_file }}'
  - '{{ sap_gce_ssh_pub_key_file }}'
  register: stat_ssh_key_files
  changed_when: false

- name: define ssh key file existence
  set_fact:
    stat_ssh_key_files_exists: "{{ stat_ssh_key_files.results | map(attribute='stat') | map(attribute='exists') | list }}"

- block:
  - name: download ssh key files
    debug:
      msg: 'Download {{ item }} from bucket not yet implemented'
    loop:
    - '{{ sap_gce_ssh_priv_key_file }}'
    - '{{ sap_gce_ssh_pub_key_file }}'
  - name: ensure ssh key file directory is present
    file:
      path: '{{ sap_gce_ssh_priv_key_file | dirname }}'
      mode: 0700
      state: directory
  - name: clean up stale ssh key file
    file:
      path: '{{ item }}'
      state: absent
    loop:
    - '{{ sap_gce_ssh_priv_key_file }}'
    - '{{ sap_gce_ssh_pub_key_file }}'
    when: false in stat_ssh_key_files_exists and true in stat_ssh_key_files_exists
  - name: generate key files
    command: |
      ssh-keygen -t rsa -N '' -m pem -f {{ sap_gce_ssh_priv_key_file }}
    args:
      creates: '{{ sap_gce_ssh_priv_key_file }}'
  - name: store ssh key files
    debug:
      msg: 'Upload {{ item | basename }} to bucket not yet implemented'
    loop:
    - '{{ sap_gce_ssh_priv_key_file }}'
    - '{{ sap_gce_ssh_pub_key_file }}'
  when: false in stat_ssh_key_files_exists

- name: deploy infrastructure with terraform
  terraform:
    backend_config:
      bucket: '{{ sap_tf_state_bucket }}'
      prefix: '{{ sap_tf_state_bucket_prefix }}'
    force_init: true
    project_path: '{{ sap_tf_project_path }}'
    state: '{{ sap_state }}'
    variables: '{{ sap_tf_variables_defaults | combine(sap_tf_variables) }}'
  register: terraform

- name: flatten inventory map into a list of maps
  # Convert { "abc": ["10.10.10.10", "10.10.10.11"], "xyz": ["10.10.10.12"] } into:
  # [
  #   { "group": "abc", "host": "10.10.10.10" },
  #   { "group": "abc", "host": "10.10.10.11" },
  #   { "group": "xyz", "host": "10.10.10.12" }
  # ]
  set_fact:
    inventory_hosts: |
      {{ inventory_hosts | default([]) }} + {% set j = joiner(",") %}
        [{% for host in item.value %}{{ j() }}{ "group": "{{ item.key }}", "host": "{{ host }}" }{% endfor %}]
  with_dict: '{{ terraform.outputs.inventory.value }}'

- name: build inventory
  add_host:
    name: '{{ item.host }}'
    ansible_user: '{{ sap_gce_ssh_user }}'
    ansible_ssh_private_key_file: '{{ sap_gce_ssh_priv_key_file }}'
    terraform: '{{ terraform }}'
    groups: '{{ item.group }}'
  loop: '{{ inventory_hosts }}'
  changed_when: false

- name: wait for hosts
  command: >-
    ssh -i {{ sap_gce_ssh_priv_key_file }} -o StrictHostKeyChecking=no
    {{ sap_gce_ssh_user }}@{{ item.host }} exit
  register: can_ssh
  retries: 12
  delay: 10
  until: can_ssh is succeeded
  loop: '{{ inventory_hosts }}'
  changed_when: false
