gcloud_install_dir: /usr/local
package_list:
  - "@base"
  - "@compat-libraries"
  - "@large-systems"
  - "@network-file-system-client"
  - "@performance"
  - uuidd
  - tcsh
  - psmisc
  - compat-sap-c++-5
  - compat-sap-c++-6
  - compat-sap-c++-7    # Required for Hana
  - compat-sap-c++-9
  - libatomic
