---
- name: include base primary tasks
  include_role:
    name: base
- name: include storage primary tasks
  include_role:
    name: storage-bkup
  vars:
    swapon: True
    disks:
      - { name: sapmnt, partition_path : sapmnt }
      - { name: usrsap, partition_path : usrsap }
      - { name: swap, partition_path : swap }
    logvols:
      sapmnt:
        size: "{{ sap_nw_sapmnt_disk_size - 1 }}G"
        vol: "sapmnt"
        mountpoint: /sapmnt
      usrsap:
        size: "{{ sap_nw_usrsap_disk_size - 1 }}G"
        vol: usrsap
        mountpoint: /usr/sap
    swapvols:
      swap:
        size: "{{ sap_nw_swap_disk_size - 1 }}G"
        vol: swap
        mountpoint: /swap
- name: include nw-pre primary tasks
  include_role:
    name: nw-pre
  vars:
    nw_bucket: "{{ sap_nw_install_files_bucket }}"
    folder: "{{ sap_nw_std_bucket_prefix }}"
    storage: "{{ sap_nw_storage_files }}"
    cloudsdk_python_export_path: "{{ sap_nw_cloudsdk_python_export_path }}"
- name: include nw primary tasks
  include_role:
    name: nw
