---

- name: SAP HANA deploy
  hosts: 127.0.0.1
  connection: local
  roles:
  - role: forminator
    vars:
      sap_tf_state_bucket: '{{ sap_hana_state_bucket }}'
      sap_tf_state_bucket_prefix: '{{ sap_hana_instance_name }}'
      sap_tf_project_path: ./tf
      sap_state: '{{ state | default("present") }}'
      sap_tf_variables:
        boot_disk_size: '{{ sap_hana_boot_disk_size | default(30) }}'
        instance_name: '{{ sap_hana_instance_name }}'
        instance_type: '{{ sap_hana_instance_type }}'
        linux_image_family: '{{ sap_hana_source_image_family }}'
        linux_image_project: '{{ sap_hana_source_image_project }}'
        project_id: '{{ sap_hana_project_id }}'
        service_account_email: '{{ sap_hana_service_account_email }}'
        subnetwork: '{{ sap_hana_subnetwork }}'
        subnetwork_project: '{{ sap_hana_subnetwork_project_id | default("") }}'
        zone: '{{ sap_hana_zone }}'

- name: SAP HANA configure
  hosts: hana
  become: yes
  roles:
  - role: sap-hana-scaleup
