---

- name: SAP HANA deploy
  hosts: 127.0.0.1
  connection: local
  roles:
  - role: forminator
    vars:
      sap_tf_project_path: ./tf
      sap_state: '{{ state | default("present") }}'
      sap_tf_variables:
        project_id: '{{ sap_project_id }}'
        sap_hana_autodelete_boot_disk: '{{ sap_hana_autodelete_boot_disk | default("false") }}'
        sap_hana_boot_disk_size: '{{ sap_hana_boot_disk_size | default(30) }}'
        sap_hana_boot_disk_type: '{{ sap_hana_boot_disk_type | default("pd-ssd") }}'
        sap_hana_instance_name: '{{ sap_hana_instance_name }}'
        sap_hana_instance_type: '{{ sap_hana_instance_type | default("n1-highmem-32") }}'
        sap_hana_install_files_bucket: '{{ sap_hana_install_files_bucket }}'
        sap_hana_network_tags: '{{ sap_hana_network_tags | default([]) }}'
        sap_hana_service_account_email: '{{ sap_hana_service_account_email }}'
        sap_hana_use_public_ip: '{{ sap_hana_use_public_ip | default("false") }}'
        source_image_family: '{{ sap_source_image_family }}'
        source_image_project: '{{ sap_source_image_project }}'
        subnetwork: '{{ sap_subnetwork }}'
        subnetwork_project: '{{ sap_subnetwork_project_id | default("") }}'
        zone: '{{ sap_zone }}'

- name: SAP HANA configure
  hosts: hana
  become: yes
  roles:
  - role: sap-hana-scaleup
