- hosts: all
  become: true
  vars:
    awx_project_name: SAP
    awx_projects_dir: /var/lib/awx/projects
    awx_project_subdir: sap-iac
    awx_project_path: '{{ awx_projects_dir }}/{{ awx_project_subdir }}'
  tasks:
  - block:
    - name: copy git repo ssh key file
      copy:
        src: '{{ playbook_dir }}/id_rsa'
        dest: /tmp/id_rsa
        mode: '0600'
    - name: clone git repository
      git:
        accept_hostkey: true
        depth: 1
        dest: '{{ awx_project_path }}'
        repo: '{{ git_repo }}'
        ssh_opts: -i /tmp/id_rsa
    always:
    - name: remove git repo ssh key file
      file:
        path: /tmp/id_rsa
        state: absent
  - name: define job directories
    shell: |
      find {{ awx_project_path }}/stacks -name awx_survey_spec.json | awk -F / '{print $(NF-1)}'
    register: job_directories
  - name: wait for tower to initialize
    shell: |
      docker logs awx_task 2>&1 | grep 'Demo Credential, Inventory, and Job Template added'
    register: tower_initialized
    retries: 60
    delay: 15
    until: tower_initialized is succeeded
    changed_when: false
  - name: delete demo tower job template
    tower_job_template:
      job_type: run
      name: Demo Job Template
      playbook: playbook.yml
      project: Demo Project
      state: absent
      tower_host: http://localhost
      tower_username: admin
      tower_password: password
      validate_certs: false
    failed_when: false
  - name: delete demo tower project
    tower_project:
      name: Demo Project
      organization: Default
      state: absent
      tower_host: http://localhost
      tower_username: admin
      tower_password: password
      validate_certs: false
    failed_when: false
  - name: delete demo tower inventory
    tower_inventory:
      name: Demo Inventory
      organization: Default
      state: absent
      tower_host: http://localhost
      tower_username: admin
      tower_password: password
      validate_certs: false
    failed_when: false
  - name: add tower project
    tower_project:
      name: '{{ awx_project_name }}'
      local_path: '{{ awx_project_subdir }}'
      organization: Default
      scm_type: manual
      tower_host: http://localhost
      tower_username: admin
      tower_password: password
      validate_certs: false
  - name: add tower localhost inventory
    tower_inventory:
      name: localhost
      organization: Default
      tower_host: http://localhost
      tower_username: admin
      tower_password: password
      validate_certs: false
  - name: add host to tower localhost inventory
    tower_host:
      inventory: localhost
      name: localhost
      tower_host: http://localhost
      tower_username: admin
      tower_password: password
      validate_certs: false
  - name: read tower survey specs
    slurp:
      src: '{{ awx_project_path }}/stacks/{{ item }}/awx_survey_spec.json'
    register: job_survey_specs
    loop: '{{ job_directories.stdout_lines }}'
  - name: add tower job templates
    tower_job_template:
      name: '{{ item.0 }}'
      concurrent_jobs_enabled: true
      inventory: localhost
      job_type: run
      playbook: 'stacks/{{ item.0 }}/playbook.yml'
      project: '{{ awx_project_name }}'
      survey_enabled: true
      survey_spec: '{{ item.1 }}'
      tower_host: http://localhost
      tower_username: admin
      tower_password: password
      validate_certs: false
    loop: '{{ job_directories.stdout_lines | zip(job_survey_specs.results | map(attribute="content") | map("b64decode")) | list }}'
